### ISSUE TITLE
whether can use your pre-trained model to do fine-tune task for mandarin phoneme (with tone) recognition  

### ISSUE THREAD

**Issue by elisonlau** [kehanlu/Mandarin-Wav2Vec2#2]
Hi 

I found your pre-trained model focus on mandarin, so exciting, cause i want to do task of phoneme recognition on mandarin model.

But when i did the following procedure , found it's doesnt working .

<img width="1034" alt="Screenshot 2023-12-22 at 12 43 03" src="https://github.com/kehanlu/Mandarin-Wav2Vec2/assets/35951559/e857597e-e8ba-4221-bcbd-2af93c5d485f">

The model has happened lots of errors!!!

Question: I wonder the model is fit for this fine-tune or not ,or there is something wrong with the config-file?
                 Do you have some useful-tips?

Thanks and looking forward to U reply
Elison

**Comment by kehanlu** [comment]
The config file is for finetuning ASR on AISHELL1 dataset using ESPNet toolkit.  We've also released the pre-trained model weights for Fairseq, but you may have to use your own config files.

Hope this can help you!
