### ISSUE TITLE
如何使用预训练权重推理

### ISSUE THREAD

**Issue by ChengsongLu** [kehanlu/Mandarin-Wav2Vec2#3]
你好，请问如何使用这边提供的预训练模型进行本地推理呢？

**Comment by kehanlu** [comment]
你好，
你可以參考 README 的範例程式碼使用 Huggingface Transformers 做推理

https://github.com/kehanlu/Mandarin-Wav2Vec2#fine-tuned-ctc-model

**Comment by ChengsongLu** [comment]
我想用这个作特征提取，请问如何获取encoder输出呢？十分感谢！
